language: php

php:
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src --standard=psr12 -sp
  - ./vendor/bin/phpstan analyse src tests --level=4

after_script:
  - php vendor/bin/coveralls
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-west-2"  
  app: "great"
  env: "Great-env"
  bucket_name: "elasticbeanstalk-us-west-2-589579859658"
  on:
    branch: master
